---
env:
  TESTBENCH_ENTITY: halfAdder

name: GHDL Testbench
on: [push]
jobs:
  Student-Testbench:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup GHDL nightly
        uses: ghdl/setup-ghdl@v1
        with:
          version: nightly
          backend: llvm
          investigate: true
      - run: ghdl --version
      - run: ghdl analyze -v src/${TESTBENCH_ENTITY}.vhd
      - run: ghdl analyze -v src/${TESTBENCH_ENTITY}_tb.vhd
      - run: ls -R
      - run: ghdl elaborate -v ${TESTBENCH_ENTITY}_tb
      - run: ghdl run -v ${TESTBENCH_ENTITY}_tb --assert-level=error --stop-time=1us
